name: Test OAuth Mock Server Action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup OAuth Mock Server
        uses: ./
        with:
          port: 8080
          client_id: test-client
          client_secret: test-secret
      - name: Test OAuth Mock Server
        run: |
          curl -I http://localhost:8080/authorize?client_id=test-client&redirect_uri=http://localhost:8081/callback&response_type=code&scope=openid%20profile%20email&state=state123
      - name: Run Other Tests
        run: |
          # Add your other test steps here
          # The OAuth mock server will be running in the background